### ISSUE TITLE
.angular-cli.json modification

### ISSUE THREAD

**Issue by Koesters** [Developer-Plexscape/cesium-angular-example#1]
I had to change the .angular-cli.json redirects to below to get it working

```
{ 
          "glob": "**/*", 
          "input": "../node_modules/cesium/Build/Cesium", 
          "output": "./" 
        },
        { 
          "glob": "**/*", 
          "input": "../node_modules/cesium/Source", 
          "output": "./assets/cesium" 
        },
```
Directing from ../node_modules/cesium/Build/Cesium to ./assets/cesium
spits out millions of 404's

Sending ../node_modules/cesium/Source to ./ spits out an Elipsoid.js failure message as seen here.
#https://github.com/mmacaula/cesium-webpack/issues/4#issuecomment-301544031
Above way works

```
> Angular CLI: 1.7.4
> Node: 9.10.0
> OS: win32 x64
> Angular: 5.2.9
> ... animations, common, compiler, compiler-cli, core, forms
> ... http, language-service, platform-browser
> ... platform-browser-dynamic, router
> 
> @angular/cli: 1.7.4
> @angular-devkit/build-optimizer: 0.3.2
> @angular-devkit/core: 0.3.2
> @angular-devkit/schematics: 0.3.2
> @ngtools/json-schema: 1.2.0
> @ngtools/webpack: 1.10.2
> @schematics/angular: 0.3.2
> @schematics/package-update: 0.3.2
> typescript: 2.5.3
> webpack: 3.11.0                    
```

**Comment by bampakoa** [comment]
Hey @Koesters thanks very much for your feedback! We are currently using a very basic cesium viewer object that actually works with the current setup. Would you mind share some of your code so that we can have a look on the issue?

**Comment by bampakoa** [comment]
Hey @Koesters thanks very much for your feedback! Which version of Cesium are you using?

**Comment by Koesters** [comment]
"cesium": "^1.44.0",

while deploying there is also an issue with internal links going to Assets and webpack only making an assets folder. This was easily solved with a symlink. 

`ln -s  assets Assets`

**Comment by bampakoa** [comment]
@Koesters thanks again for the info. This is due to a bug of Cesium 1.44 where it does not respect the value of CESIUM_BASE_URL that we set in `main.ts`. [Here](https://github.com/AnalyticalGraphicsInc/cesium/issues/6411) is the issue that explains the whole story.
