### ISSUE TITLE
README: add tutorial to add cesium to a current app

### ISSUE THREAD

**Issue by CHBaker** [Developer-Plexscape/cesium-angular-example#2]
Currently the docs do not explain how to add Cesium to your angular app.
I would be happy to help contribute, I just got it working in my own app.

**Comment by bampakoa** [comment]
@CHBaker thank you very much for your feedback! This repo was initially created as an accompanying material of [this](https://cesium.com/blog/2018/03/12/cesium-and-angular/) blog post. Nevertheless, a related README doc is something that's missing. If you wish to contribute, we would be very happy to review and merge your PR.

**Comment by CHBaker** [comment]
awesome
