### ISSUE TITLE
FEATURE: include most recent typings with this repo

### ISSUE THREAD

**Issue by CHBaker** [Developer-Plexscape/cesium-angular-example#3]
I believe it would be beneficial to make this repo function with @types/cesium from definitelytyped as well. I could include that in the docs pull also.

only one issue, it has stopped working suddenly, I'm tracking an [issue with repro steps here](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33985)

if you have any idea on fixes for this we could work it out together, and this would be a great resource for Angular Typescript Cesium users

**Comment by bampakoa** [comment]
@CHBaker that is a nice idea but consider this:

1. These are not official typings from Cesium. There is an effort that has began to create official types from within the Cesium code, based on the JSDoc tags. You can find more details here https://github.com/AnalyticalGraphicsInc/cesium/issues/5717#issuecomment-472854250 
2. It is preferable to let the end users decide upon the types that will use (they could have even created their own types)

On the other hand, we could mention on the docs about the existence of typings in the types repository and how can be used in this example. What do you think?

**Comment by CHBaker** [comment]
Sounds good to me, I see your point. I have seen that issue, it seems there is a race on who finishes typings first, then it will be integrated on both ends

**Comment by CHBaker** [comment]
Sounds good to me, I see your point. I have seen that issue, it seems there is a race on who finishes typings first, then it will be integrated on both ends
