### ISSUE TITLE
problems with new version of angular?

### ISSUE THREAD

**Issue by ZhiminXu** [Developer-Plexscape/cesium-angular-example#5]
Hello, I read the code of the master branch and tried to creat a new project from scratch.

The dependencies is as follow.

```javascript
"dependencies": {
    "@angular/animations": "~10.0.4",
    "@angular/common": "~10.0.4",
    "@angular/compiler": "~10.0.4",
    "@angular/core": "~10.0.4",
    "@angular/forms": "~10.0.4",
    "@angular/platform-browser": "~10.0.4",
    "@angular/platform-browser-dynamic": "~10.0.4",
    "@angular/router": "~10.0.4",
    "cesium": "^1.71.0",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.3",
    "@angular/cli": "~10.0.3",
    "@angular/compiler-cli": "~10.0.4",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5"
  }
```

I installed cesium, generated a directive and created the same appCesium div with css. But I got some errors when using ng serve.

> ERROR in ./node_modules/_cesium@1.71.0@cesium/Source/Core/Resource.js
> Module not found: Error: Can't resolve 'http' in 'C:\Users\xzm\Desktop\test\node_modules\_cesium@1.71.0@cesium\Source\Core'

> ERROR in ./node_modules/_cesium@1.71.0@cesium/Source/Core/Resource.js
> Module not found: Error: Can't resolve 'https' in 'C:\Users\xzm\Desktop\test\node_modules\_cesium@1.71.0@cesium\Source\Core'

> ERROR in ./node_modules/_cesium@1.71.0@cesium/Source/Core/Resource.js
> Module not found: Error: Can't resolve 'zlib' in 'C:\Users\xzm\Desktop\test\node_modules\_cesium@1.71.0@cesium\Source\Core'

To solve the problem, I  added a script in angular.json and changed the way of using Cesium.

```javacript
"scripts": [
    "node_modules/cesium/Build/Cesium/Cesium.js"
]
```

For declaration, instead of 

`import { Viewer } from 'cesium';`

 I used 

`declare const Cesium: any;`

The problem solved, but I got the cesium map like this.
![image](https://user-images.githubusercontent.com/22171494/88038072-4dccc180-cb78-11ea-96e1-fd219d2635ea.png)

Does anyone know where the problem is?

**Comment by bampakoa** [comment]
@ZhiminXu I tried your `package.json` dependencies but I could not reproduce the errors that you get. Bear in mind that this repository uses **@angular-builders/custom-webpack**, a custom webpack builder, to eliminate warnings that emit from Cesium. Have you tried to clone the repository and test it as is?  

However, the display of your map is due to the fact that you do not load the Cesium stylesheet in the `angular.json` file. You can see [here](https://github.com/Developer-Plexscape/cesium-angular-example/blob/03cb7007b5b761523680d4fe97cada458dfb3426/angular.json#L32) for more details.

If you have any other question please let me know!

**Comment by ZhiminXu** [comment]
@bampakoa Thanks for your relpy.

I do tried to clone the repository and test it as is.  But I got an error and similiar result as shown below. That is why i tried to create a new project from scratch.

![image](https://user-images.githubusercontent.com/22171494/88070664-83d46a80-cba5-11ea-98b9-5df8ed25888a.png)

**Comment by ZhiminXu** [comment]
@bampakoa I started the project from repository twice and the error disappeared.  But the cesium map was still like before.

**Comment by bampakoa** [comment]
@ZhiminXu is seems that there were some problems with the Angular itself. In such cases, what I do, is delete `node_modules` and `package-lock.json` and make a fresh `npm install`.

>But the cesium map was still like before.

You need to include Cesium CSS stylesheet for that to work as I stated in my previous comment.

**Comment by ZhiminXu** [comment]
@bampakoa 

> You need to include Cesium CSS stylesheet for that to work as I stated in my previous comment.

In my previous comment, the code I used was cloned from the repository.

**Comment by bampakoa** [comment]
@ZhiminXu then it should work normally. If you can make your code public, in any means, I would be happy to help on that.

**Comment by ZhiminXu** [comment]
@bampakoa Thanks.
 
I tested on another computer with nodejs v12.13.1 and it was OK. The version on mine was v12.18.2, so I reinstalled v12.13.1 and got the right cesium map too. So this problem may be related to the version of nodejs.

**Comment by bampakoa** [comment]
Awesome @ZhiminXu! I am glad that it finally worked.
